[Animations]
NumberOfAnimations=4

Animation1=Wings_Fold
Animation2=Wings_Extend
Animation3=Gear_Extend
Animation4=Gear_Retract

[Wings_Fold]
NumberOfSequencesToPlay=5
Sequence1=Hub_Rotate
Sequence1_Model=Rotor_Hub
Sequence2=Blade_1_Fold
Sequence2_Model=Blade_1
Sequence3=Blade_2_Fold
Sequence3_Model=Blade_2
Sequence4=Blade_3_Fold
Sequence4_Model=Blade_3
Sequence5=Blade_4_Fold
Sequence5_Model=Blade_4


[Wings_Extend]
NumberOfSequencesToPlay=5
Sequence1=Hub_Unrotate
Sequence1_Model=Rotor_Hub
Sequence2=Blade_1_Unfold
Sequence2_Model=Blade_1
Sequence3=Blade_2_Unfold
Sequence3_Model=Blade_2
Sequence4=Blade_3_Unfold
Sequence4_Model=Blade_3
Sequence5=Blade_4_Unfold
Sequence5_Model=Blade_4

[Gear_Extend]
NumberOfSequencesToPlay=4
Sequence1=Left_Gear_Extend
Sequence1_Model=Left_Gear
Sequence2=Left_Strut_Extend
Sequence2_Model=Left_Gear_Strut
Sequence3=Right_Gear_Extend
Sequence3_Model=Right_Gear
Sequence4=Right_Strut_Extend
Sequence4_Model=Right_Gear_Strut

[Gear_Retract]
NumberOfSequencesToPlay=4
Sequence1=Left_Gear_Retract
Sequence1_Model=Left_Gear
Sequence2=Left_Strut_Retract
Sequence2_Model=Left_Gear_Strut
Sequence3=Right_Gear_Retract
Sequence3_Model=Right_Gear
Sequence4=Right_Strut_Retract
Sequence4_Model=Right_Gear_Strut



[Hub_Rotate]
NumberOfSteps=2
Time1=0
RotationZ1=0
Smoothness1=EaseInOut
Time2=5 
RotationZ2=-135
Smoothness2=EaseInOut

[Hub_Unrotate]
NumberOfSteps=3
Time1=0
RotationZ1=-135
Smoothness1=EaseInOut
Time2=5 
RotationZ2=-135
Smoothness2=EaseInOut
Time3=10 
RotationZ3=0
Smoothness3=EaseInOut

[Blade_1_Fold]
NumberOfSteps=3
Time1=0
RotationZ1=175
Smoothness1=EaseInOut
Time2=5 
RotationZ2=175
Smoothness2=EaseInOut
Time3=10 
RotationZ3=314
Smoothness3=EaseInOut

[Blade_1_Unfold]
NumberOfSteps=3
Time1=0
RotationZ1=314
Smoothness1=EaseInOut
Time2=5 
RotationZ2=175
Smoothness2=EaseInOut
Time3=10 
RotationZ3=175
Smoothness3=EaseInOut

[Blade_2_Fold]
NumberOfSteps=3
Time1=0 
RotationZ1=-95
Smoothness1=EaseInOut
Time2=5
RotationZ2=-95
Smoothness2=EaseInOut
Time3=10
RotationZ3=-44
Smoothness3=EaseInOut

[Blade_2_Unfold]
NumberOfSteps=3
Time1=0 
RotationZ1=-44
Smoothness1=EaseInOut
Time2=5
RotationZ2=-95
Smoothness2=EaseInOut
Time3=10
RotationZ3=-95
Smoothness3=EaseInOut

[Blade_3_Fold]
NumberOfSteps=3
Time1=0
RotationZ1=-5
Smoothness1=EaseInOut
Time2=5 
RotationZ2=-5
Smoothness2=EaseInOut
Time3=10
RotationZ3=-49
Smoothness3=EaseInOut

[Blade_3_Unfold]
NumberOfSteps=3
Time1=0
RotationZ1=-49
Smoothness1=EaseInOut
Time2=5 
RotationZ2=-5
Smoothness2=EaseInOut
Time3=10
RotationZ3=-5
Smoothness3=EaseInOut

[Blade_4_Fold]
NumberOfSteps=3
Time1=0
RotationZ1=85
Smoothness1=EaseInOut
Time2=5 
RotationZ2=85
Smoothness2=EaseInOut
Time3=10
RotationZ3=-48
Smoothness3=EaseInOut

[Blade_4_Unfold]
NumberOfSteps=3
Time1=0
RotationZ1=-48
Smoothness1=EaseInOut
Time2=5 
RotationZ2=85
Smoothness2=EaseInOut
Time3=10
RotationZ3=85
Smoothness3=EaseInOut

###Gear Struts Retraction

[Left_Gear_Extend]
NumberOfSteps=2
Time1=0 
RotationZ1=133
Smoothness1=EaseInOut
Time2=3 
RotationZ2=72
Smoothness2=EaseInOut

[Left_Strut_Extend]
NumberOfSteps=2
Time1=0 
RotationZ1=147
Smoothness1=EaseInOut
Time2=3
RotationZ2=72
Smoothness2=EaseInOut

[Right_Gear_Extend]
NumberOfSteps=2
Time1=0 
RotationZ1=-133
Smoothness1=EaseInOut
Time2=3 
RotationZ2=-72
Smoothness2=EaseInOut


[Right_Strut_Extend]
NumberOfSteps=2
Time1=0 
RotationZ1=-147
Smoothness1=EaseInOut
Time2=3
RotationZ2=-72
Smoothness2=EaseInOut

[Left_Gear_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=72
Smoothness1=EaseInOut
Time2=3 
RotationZ2=133
Smoothness2=EaseInOut

[Left_Strut_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=72
Smoothness1=EaseInOut
Time2=3
RotationZ2=147
Smoothness2=EaseInOut

[Right_Gear_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=-72
Smoothness1=EaseInOut
Time2=3 
RotationZ2=-133
Smoothness2=EaseInOut


[Right_Strut_Retract]
NumberOfSteps=2
Time1=0 
RotationZ1=-72
Smoothness1=EaseInOut
Time2=3
RotationZ2=-147
Smoothness2=EaseInOut