[Animations]
NumberOfAnimations=8
Animation1=HangarOpenAnim
Animation2=HangarCloseAnim
Animation3=TorpedoDoorOpenL
Animation4=TorpedoDoorCloseL
Animation5=TorpedoDoorOpenR
Animation6=TorpedoDoorCloseR
Animation7=Elevator1LaunchPoint1
Animation8=RecoveryPoint1Elevator1

[HangarOpenAnim]
NumberOfSequencesToPlay=2
Sequence1=HangarOpenDoor1AnimSequence
Sequence1_Model=HangarDoor_2
Sequence2=HangarOpenDoor2AnimSequence
Sequence2_Model=HangarDoor_1

[HangarCloseAnim]
NumberOfSequencesToPlay=2
Sequence1=HangarCloseDoor1AnimSequence
Sequence1_Model=HangarDoor_2
Sequence2=HangarCloseDoor2AnimSequence
Sequence2_Model=HangarDoor_1

[TorpedoDoorOpenL]
NumberOfSequencesToPlay=2
Sequence1=TorpedoDoorOpenSequence
Sequence1_Model=TorpedoDoor_1
Sequence2=TorpedoMountOpenLSequence
Sequence2_Model=TorpedoMount_1

[TorpedoDoorOpenR]
NumberOfSequencesToPlay=2
Sequence1=TorpedoDoorOpenSequence
Sequence1_Model=TorpedoDoor_2
Sequence2=TorpedoMountOpenRSequence
Sequence2_Model=TorpedoMount_2

[TorpedoDoorCloseL]
NumberOfSequencesToPlay=2
Sequence1=TorpedoDoorCloseSequence
Sequence1_Model=TorpedoDoor_1
Sequence2=TorpedoMountCloseLSequence
Sequence2_Model=TorpedoMount_1

[TorpedoDoorCloseR]
NumberOfSequencesToPlay=2
Sequence1=TorpedoDoorCloseSequence
Sequence1_Model=TorpedoDoor_2
Sequence2=TorpedoMountCloseRSequence
Sequence2_Model=TorpedoMount_2

[Elevator1LaunchPoint1]
NumberOfSequencesToPlay=1
Sequence1=Elevator1LaunchPoint1Sequence
Sequence1_Model=SpawnedObject

[RecoveryPoint1Elevator1]
NumberOfSequencesToPlay=1
Sequence1=RecoveryPoint1Elevator1Sequence
Sequence1_Model=SpawnedObject

[------------------------------ Sequences ------------------------------]
[HangarOpenDoor1AnimSequence]
NumberOfSteps=2
Time1=0
PositionX1=0
Smoothness1=EaseInOut
Time2=5
PositionX2=0.058
Smoothness2=EaseInOut

[HangarOpenDoor2AnimSequence]
NumberOfSteps=2
Time1=0
PositionX1=-0.05
Smoothness1=EaseInOut
Time2=5
PositionX2=0.058
Smoothness2=EaseInOut

[HangarCloseDoor1AnimSequence]
NumberOfSteps=2
Time1=0
PositionX1=0.058
Smoothness1=EaseInOut
Time2=5
PositionX2=0.0
Smoothness2=EaseInOut

[HangarCloseDoor2AnimSequence]
NumberOfSteps=2
Time1=0
PositionX1=0.058
Smoothness1=EaseInOut
Time2=5
PositionX2=-0.05
Smoothness2=EaseInOut

//-------------------------------------------------------------------------------------------

[TorpedoDoorOpenSequence]
NumberOfSteps=2
Time1=0
PositionY1=0.075
Smoothness1=EaseInOut
Time2=5
PositionY2=0.091
Smoothness2=EaseInOut

[TorpedoDoorCloseSequence]
NumberOfSteps=2
Time1=0
PositionY1=0.091
Smoothness1=EaseInOut
Time2=5
PositionY2=0.075
Smoothness2=EaseInOut

[TorpedoMountOpenLSequence]
NumberOfSteps=2
Time1=0
RotationY1=0
Smoothness1=EaseInOut
Time2=5
RotationY2=-45
Smoothness2=EaseInOut

[TorpedoMountCloseLSequence]
NumberOfSteps=2
Time1=0
RotationY1=-45
Smoothness1=EaseInOut
Time2=5
RotationY2=0
Smoothness2=EaseInOut

[TorpedoMountOpenRSequence]
NumberOfSteps=2
Time1=0
RotationY1=0
Smoothness1=EaseInOut
Time2=5
RotationY2=45
Smoothness2=EaseInOut

[TorpedoMountCloseRSequence]
NumberOfSteps=2
Time1=0
RotationY1=45
Smoothness1=EaseInOut
Time2=5
RotationY2=0
Smoothness2=EaseInOut

[------------------------------ FlightDeck Taxi Sequences ------------------------------]
# Waypoints for comparsion from the ini file. Delete this when done with anim
# Waypoints
#[Waypoint1]
#Position=-0.0311,0.145,-0.2891
#Rotation=0
#Time=1

#[Waypoint2]
#Position=-0.0311,0.145,-0.4854
#Rotation=0
#Time=6

#[Waypoint3]
#Position=-0.0311,0.145,-0.4854
#Rotation=-12
#Time=3

#[Waypoint4]
#Position=0.0,0.145,-0.6314
#Rotation=-12
#Time=6

#[Waypoint5]
#Position=0.0,0.145,-0.6314
#Rotation=0
#Time=3

[Elevator1LaunchPoint1Sequence]
NumberOfSteps=4
Time1=0                // time in seconds for the start
PositionX1=-0.0311
PositionY1=0.145
PositionZ1=-0.4854
RotationY1=0
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step

Time2=3
RotationY2=-12
Smoothness2=Linear

Time3=9
PositionX3=0
PositionZ3=-0.6314
Smoothness3=Linear

Time4=12
RotationY4=0
Smoothness4=Linear

[RecoveryPoint1Elevator1Sequence]
NumberOfSteps=4
Time1=0                // time in seconds for the start
PositionX1=0
PositionY1=0.145
PositionZ1=-0.6314
RotationY1=0
Smoothness1=Linear  // can be: Linear, EaseInOut - transition to the next step

Time2=3
RotationY2=-12
Smoothness2=Linear

Time3=9
PositionX3=-0.0311
PositionZ3=-0.4854
Smoothness3=Linear

Time4=12
RotationY4=0
Smoothness4=Linear
