[General]
HullnumberReference=Hullnumber
EmblemReference=Emblem
NationFlagReference=Flag1
NumberOfVariants=30

[Default]
ResourcesHullnumberFolder=textures/Misc/
HullnumberTexture=transparent
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1977|1997

[Variant1] # FFG-8 McInerney
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-8
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_8
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1979|2010
#CustomAirGroup=True
#usn_sh-60b=Squadron7,2

[Variant2] # FFG-28 Boone
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-28
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_14
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1987|2012
#CustomAirGroup=True
#usn_sh-60b=Squadron7,2

[Variant3] # FFG-29 Stephen W. Groves
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-29
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_14
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1988|2012
#CustomAirGroup=True
#usn_sh-60b=Squadron7,2

[Variant4] # FFG-32 John L. Hall
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-32
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_24
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1989|2012
#CustomAirGroup=True
#usn_sh-60b=Squadron7,2

[Variant5] # FFG-33 Jarrett
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-33
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_9
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1989|2011
#CustomAirGroup=True
#usn_sh-60b=Squadron4,2

[Variant6] # FFG-36 Underwood
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-36
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_24
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1983|2013
#CustomAirGroup=True
#usn_sh-60b=Squadron7,2

[Variant7] # FFG-37 Crommelin
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-37
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_9
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1983|2013
#CustomAirGroup=True
#usn_sh-60b=Squadron4,2

[Variant8] # FFG-38 Curts
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-38
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_9
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1983|2013
#CustomAirGroup=True
#usn_sh-60b=Squadron4,2

[Variant9] # FFG-39 Doyle
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-39
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_24
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1983|2011
#CustomAirGroup=True
#usn_sh-60b=Squadron7,2

[Variant10] # FFG-40 Halyburton
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-40
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_6
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1984|2014
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant11] # FFG-41 McClusky
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-41
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_1
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1983|2015
#CustomAirGroup=True
#usn_sh-60b=Squadron6,2

[Variant12] # FFG-42 Klakring
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-42
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_6
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1983|2013
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant13] # FFG-43 Thach
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-43
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=surfron_1
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1984|2013
#CustomAirGroup=True
#usn_sh-60b=Squadron6,2

[Variant14] # FFG-45 De Wert
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-45
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_6
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1983|2014
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant15] # FFG-46 Rentz
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-46
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_1
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1984|2014
#CustomAirGroup=True
#usn_sh-60b=Squadron6,2

[Variant16] # FFG-47 Nicholas
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-47
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_20
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1984|2014
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant17] # FFG-48 Vandegrift
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-48
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=surfron_1
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1984|2015
#CustomAirGroup=True
#usn_sh-60b=Squadron6,2

[Variant18] # FFG-49 Robert G. Bradley
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-49
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_20
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1984|2014
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant19] # FFG-50 Taylor
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-50
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_20
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1984|2015
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant20] # FFG-51 Gary
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-51
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=surfron_1
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1984|2015
#CustomAirGroup=True
#usn_sh-60b=Squadron6,2

[Variant21] # FFG-52 Carr
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-52
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_36
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1985|2013
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant22] # FFG-53 Hawes
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-53
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_36
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1985|2010
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant23] # FFG-54 Ford
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-54
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=surfron_1
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1985|2013
#CustomAirGroup=True
#usn_sh-60b=Squadron6,2

[Variant24] # FFG-55 Elrod
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-55
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=desron_36
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1985|2015
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant25] # FFG-56 Simpson
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-56
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=surfgru_4
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1985|2015
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant26] # FFG-57 Reuben James
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-57
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=surfron_1
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1986|2013
#CustomAirGroup=True
#usn_sh-60b=Squadron6,2

[Variant27] # FFG-58 Samuel B. Roberts
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-58
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=surfgru_4
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1986|2015
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant28] # FFG-59 Kauffman
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-59
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=surfgru_4
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1987|2015
#CustomAirGroup=True
#usn_sh-60b=Squadron5,2

[Variant29] # FFG-60 Rodney M. Davis
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-60
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=surfron_1
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1987|2015
#CustomAirGroup=True
#usn_sh-60b=Squadron6,2

[Variant30] # FFG-61 Ingraham
ResourcesHullnumberFolder=ships/materials/hullnumbers/
HullnumberTexture=usn_ffg-61
ResourcesEmblemFolder=ships/materials/emblem/
EmblemTexture=surfron_1
ResourcesLiveryFolder=ships/usn_ffg_oliver_hazard_perry_longhull/
LiveryTexture=usn_ffg_oliver_hazard_perry_longhull_tx
ResourcesFlagFolder=ships/materials/textures/
FlagTexture=flag_us
Nation=US
ServiceDate=1989|2015
#CustomAirGroup=True
#usn_sh-60b=Squadron6,2
